### ISSUE TITLE
Diagram for every microservice + diagram for microservices intercommunication

### ISSUE THREAD

**Issue by madalinaalexandra** [wadoteam/client-app#4]

**Comment by madalinaalexandra** [comment]
![processinput 1](https://user-images.githubusercontent.com/22093019/33336982-3f5c8830-d47a-11e7-9246-09d06affdbea.jpg)

Diagram for ProcessInput MicroService

**Comment by madalinaalexandra** [comment]
![queryingontology](https://user-images.githubusercontent.com/22093019/33337523-ddb47ff0-d47b-11e7-9539-95a7c4c88625.jpg)

Diagram for QueryingOntology MicroService

**Comment by andreijuravle** [comment]
![untitled diagram](https://user-images.githubusercontent.com/19391967/33339771-e1c7b650-d482-11e7-85f2-7bc472519c4e.jpg)

Diagram for Client Application

**Comment by andreijuravle** [comment]
![untitled diagram 1](https://user-images.githubusercontent.com/19391967/33340540-0a547066-d485-11e7-90aa-79a97e69754a.jpg)

Diagram for BuildOntology MicroService
