### ISSUE TITLE
Create pages mockups for web application

### ISSUE THREAD

**Issue by madalinaalexandra** [wadoteam/client-app#5]

**Comment by afurculita** [comment]
@andreijuravle am redenumit repository-ul in care se afla aplicatia client in "client-app" si am mutat ce ai facut tu in branch-ul "master". Poti adauga in repo si build-ul pentru a-l putea adauga pe o pagina de Github?

**Comment by afurculita** [comment]
Am incarcat eu aplicatia la https://wadoteam.github.io/client-app/dist
